# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='notes',
        ),
    ]
