# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_remove_authors_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='Mauris at laoreet dolor. Vivamus suscipit elementum dolor eget tincidunt. Sed consequat mauris at congue pharetra. Proin eu dolor risus. Nulla in laoreet lectus. Quisque malesuada quam maximus pulvinar egestas. Nunc gravida risus ligula, non ornare tortor pellentesque vitae. Aliquam ut turpis tristique, aliquet justo euismod, semper orci. Quisque posuere dui venenatis erat vulputate, sed maximus nisl ullamcorper.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='desc',
            field=models.TextField(default='Mauris at laoreet dolor. Vivamus suscipit elementum dolor eget tincidunt. Sed consequat mauris at congue pharetra. Proin eu dolor risus. Nulla in laoreet lectus. Quisque malesuada quam maximus pulvinar egestas. Nunc gravida risus ligula, non ornare tortor pellentesque vitae. Aliquam ut turpis tristique, aliquet justo euismod, semper orci. Quisque posuere dui venenatis erat vulputate, sed maximus nisl ullamcorper.'),
            preserve_default=False,
        ),
    ]
